add SNO_BANNED, snote for it on client k/x-line rejection
solanum-ircd/solanum pull request #242
Opened 2021-07-11 20:52 UTC by jesopo

closes #234

2021-07-28 15:51 UTC, jesopo commented
maybe there's good enough reason to extend this to project rejected for not using SASL on a SASL only source

2021-07-31 04:56 UTC, dwfreed commented
I would say that could be done in the unauthorized snomask, and should cover any failure to meet their matching auth block requirements, not just SASL (secure comes to mind).

2021-07-31 04:56 UTC, dwfreed requested changes
This needs a line in the snomask help file

2021-08-11 15:52 UTC, dwfreed approved these changes

2021-08-11 16:08 UTC, merged