MODE +k: Return ERR_INVALIDMODEPARAM instead of stripping invalid chars or truncating
solanum-ircd/solanum pull request #258
Opened 2021-08-10 18:20 UTC by ProgVal

This is more user-friendly (prevents setting a different key than
what the other requested) and makes the behavior consistent with
InspIRCd and Ergo (and hopefully others soon).

https://github.com/ircdocs/modern-irc/pull/111

2021-08-10 22:12 UTC, edk0 requested changes
Per IRC, I think we should either accept or reject the whole mode command, not error while still actioning the rest of it.

2021-08-11 06:56 UTC, ProgVal commented
> Per IRC

Where/when? I think I missed this discussion.


`ERR_INVALIDMODEPARAM` mention which char is causing the issue so client can figure it out.

Both InspIRCd and Ergo do it like this:

```
C -> S: MODE #chan +vk bar :passphrase with spaces
S -> C: :My.Little.Server 696 bar #chan k * :Invalid key mode parameter. Syntax: <key>.
S -> C: :bar!username@127.0.0.1 MODE #chan +v :bar
```

2021-08-12 18:49 UTC, dwfreed commented
```
2021-08-10 17:03:24 < edk> yes but it's not that simple
2021-08-10 17:03:41 < edk> currently by the time we know it's an invalid key we've already started actioning the command
2021-08-10 17:03:57 < edk> and i think we should either accept the whole command or reject it
```

Timestamp is UTC; this was said about 10 minutes after you brought up this issue.

2021-08-12 18:57 UTC, ProgVal commented
Okay nevermind then I'd rather keep solanum constant with Hybrid than introduce yet another behavior

2021-08-12 18:57 UTC, closed without merging