add SNO_FARCONNECT to the help text
solanum-ircd/solanum pull request #260
Opened 2021-08-12 15:14 UTC by xfnw

snomask +F seems to be missing from the help text

2021-08-13 15:36 UTC, examknow commented
We should probably also mention that this requires `extensions/sno_farconnect` to be loaded.

2021-08-13 19:34 UTC, xfnw commented
hmm, the other entries dont mention required extensions

2021-08-13 19:41 UTC, aaronmdjones commented
Follow the convention in the `UMODE` help, and put a `?` next to snomasks that require extensions?

2021-08-14 03:31 UTC, aaronmdjones requested changes

2021-08-14 03:31 UTC, aaronmdjones commented on help/opers/snomask
> +Server notice masks: (? designates that the umode is provided
snomask, not umode.

2021-08-14 11:12 UTC, aaronmdjones approved these changes

2021-08-14 11:15 UTC, merged