send RPL_LOGGEDIN to target_p upon ENCAP SU
solanum-ircd/solanum pull request #308
Opened 2022-01-01 22:38 UTC by jesopo

intended usecase: a client receives `RPL_LOGGEDIN` on a network that supports SASL but the client knows it doesn't currently have a SASL configuration, so it prompts the user with "would you like to save your account password for this network?"

2022-02-10 14:08 UTC, A-UNDERSCORE-D submitted a review, later dismissed

2022-03-06 21:27 UTC, edk0 commented
This sends a RPL_LOGGEDIN for `(null)` if I log out. It should probably send RPL_LOGGEDOUT or nothing

2022-06-30 00:42 UTC, dwfreed requested changes
What @edk0 said; I prefer the RPL_LOGGEDOUT response.

2022-12-23 11:32 UTC, dwfreed approved these changes

2022-12-23 16:27 UTC, merged