make more snotes L_NETWIDE
solanum-ircd/solanum pull request #37
Opened 2020-10-28 15:34 UTC by jesopo

pulled out of chary PR, hope the squash merge between upstreams worked ok

2020-10-28 15:51 UTC, edk0 requested changes
Thanks for this. I think m_dline probably shouldn't be skipped—D-lines are (currently) local, there should be one netwide snote for every server that gets them.

2020-10-28 21:55 UTC, jesopo commented
some comments I forgot to bring forward from the chary PR:

I skipped over m_kill because I couldn't understand some seemingly important things, and I skipped over m_dline because the ircd-seven changes above didn't make sense (netwide snote per server?)

some changes (m_kline, m_resv, m_squit, m_xline) were basically ripped straight out of the ircd-seven changeset without me fully grokking them, because I got a bit lost in how propagation works for those

2020-10-29 15:22 UTC, edk0 commented
Ack, but I'm pretty sure the seven changes do make sense for dline. They don't all have to be `ON *`.

2020-11-08 16:26 UTC, edk0 approved these changes

2020-11-08 16:46 UTC, dwfreed requested changes
A few that should always be netwide

2020-11-08 16:46 UTC, dwfreed commented on ircd/client.c
> +			sendto_realops_snomask(SNO_GENERAL, !IsServer(client_p) ? L_NETWIDE : L_ALL,
```suggestion
			sendto_realops_snomask(SNO_GENERAL, L_NETWIDE,
```

2020-11-08 16:46 UTC, dwfreed commented on ircd/client.c
> +			sendto_realops_snomask(SNO_GENERAL, !IsServer(client_p) ? L_NETWIDE : L_ALL,
```suggestion
			sendto_realops_snomask(SNO_GENERAL, L_NETWIDE,
```

2020-11-08 16:46 UTC, dwfreed commented on ircd/sslproc.c
> +		sendto_realops_snomask(SNO_GENERAL, !IsServer(client_p) ? L_NETWIDE : L_ALL, "ssld error for %s: %s", client_p->name, reason);
```suggestion
		sendto_realops_snomask(SNO_GENERAL, L_NETWIDE, "ssld error for %s: %s", client_p->name, reason);
```

2020-11-08 19:22 UTC, dwfreed approved these changes

2020-11-08 19:30 UTC, merged