ircd/listener: return a fatal TLS alert for early rejected TLS clients
solanum-ircd/solanum pull request #412
Opened 2023-06-15 22:37 UTC by aaronmdjones

This is in furtherance of commit 3fdf26aa19628d5e12a3 which added functionality to reply with a TLS record layer alert for D-Lined TLS clients. It turns out that there are other plaintext error messages in this same function that should receive the same treatment.

Also move another error string to a variable and use a compile-time optimised-out strlen for it too, to use the same approach as an existing error string.

2023-06-16 13:34 UTC, jillest commented on ircd/listener.c
> +			rb_write(F, sslerrcode, sizeof(sslerrcode));
Alert 80 "internal_error" would be a better choice for this situation (but not any of the others below).

2023-06-16 13:34 UTC, jillest commented on ircd/listener.c
`check_reject` above will add the client to a list; code in ircd/reject.c will later send error messages without SSL negotiation as well. Fitting in with the theme of this pull request, those should be replaced with TLS alerts as well.

2023-11-07 22:23 UTC, dwfreed requested changes

2023-11-07 22:23 UTC, dwfreed commented on ircd/reject.c
> +			rb_write(ddata->F, ssldeniederrcode, sizeof(ssldeniederrcode));
This misses the `deref_conf` below when `ddata->aconf` is not NULL.

2023-11-07 22:45 UTC, dwfreed approved these changes

2023-11-07 23:52 UTC, merged